<?php
namespace app\commands;

use Yii;
use app\models\Ticket;
use yii\console\Controller;
use yii\helpers\Console;

/**
 * 购票
 * Class TicketController
 * @package app\commands
 */
class TicketController extends Controller
{

    private $_ticketBase;
    private $_ticketInfo;
    private $_seatType;
    private $_ticketQuery;
    private $_ticketNotify;
    public function beforeAction($action)
    {
        $this->_ticketBase = \Yii::$app->params['TicketBase'];
        $this->_ticketInfo = \Yii::$app->params['TicketInfo'];
        $this->_ticketQuery = \Yii::$app->params['TicketQuery'];
        $this->_seatType = \Yii::$app->params['SeatType'];
        $this->_ticketNotify = \Yii::$app->params['TicketNotify'];
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 初始化
     * @throws \Exception
     */
    public function actionIndex()
    {
        $username = $this->_ticketBase['username'];
        $password = $this->_ticketBase['password'];
        $cookieArray = [];
        if(Ticket::checkUser($username,$password,$cookieArray)){
            date_default_timezone_set('PRC');
            $hour = date('H');
            if($hour <= $this->_ticketBase['isTicket'][0] || $hour >= $this->_ticketBase['isTicket'][1]){
                sdt_output('12306系统维护中【维护时间:23:00-07:00】');
                exit;
            }
            $from_name = $this->_ticketQuery['from_station'];
            $to_name = $this->_ticketQuery['to_station'];
            $ticketInfo['from_name'] = $from_name;
            $ticketInfo['to_name'] = $to_name;
            $ticketInfo['train_date'] = $this->_ticketQuery['train_date'];
            $ticketInfo['back_train_date'] = '';
            $ticket = loadConfig('ticket');
            $ticketInfo['from_code'] = $ticket['address'][$from_name];
            $ticketInfo['to_code'] = $ticket['address'][$to_name];

            if($this->_ticketBase['auto'] == TRUE){
                $is_auto = $this->_ticketBase ? '自动' : '手动';
                $ticket = $this->_ticketQuery;
                $trips_num = $this->_ticketInfo['trips_num'];
                $passenger = $this->_ticketInfo['passenger'];
                $seat_type = $this->_seatType[$this->_ticketInfo['seat_index']]['name'];
                sdt_output("********************* 初始化 *********************");
                sdt_output("购票类型：{$is_auto}");
                sdt_output("短信提醒：{$this->_ticketNotify['Sms']['is_open']}");
                sdt_output("邮件提醒：{$this->_ticketNotify['Email']['is_open']}");
                sdt_output("********************* 当前配置 *********************");
                sdt_output("购票时间：{$ticket['train_date']}");
                sdt_output("出发站：{$ticket['from_station']} 到达站：{$ticket['to_station']}");
                sdt_output("筛选车次：{$trips_num}");
                sdt_output("乘车人：{$passenger}");
                sdt_output("坐席：{$seat_type}");
                sdt_output("********************* 开始执行 *********************");
                if(!isset($this->_ticketInfo['trips_num'])){
                    sdt_output('请填写购买的车次!');
                }
                $tripsCode = $this->_ticketInfo['trips_num'];
            }else{
                $tripsResult = Ticket::ticketQuery($ticketInfo);
                sdt_output('请选择有效车次序号!');
                $tripsIndex = sdt_input();
                if (!isset($tripsResult[$tripsIndex - 1])) {
                    sdt_output('序号不存在请重试!');
                }
                //选定车次
                $tripsCode = $tripsResult[$tripsIndex - 1]['cc'];
                sdt_output("您选择的车次是：{$tripsCode}");
            }
            $seatType = Ticket::getSeatType();
            $passenger = Ticket::getPassenger($seatType);
            Ticket::brushTicket($ticketInfo,$passenger,$tripsCode,$seatType);
            sdt_output("********************* 结束执行 *********************");
        }
    }
}
